#!/bin/bash

current_volume=$(/usr/bin/wpctl get-volume @DEFAULT_AUDIO_SINK@)

volume="$(echo $current_volume | cut -f 2 -d " " | sed 's/\.//g')"

if [[ $current_volume == *"MUTED"* ]]; then
    dunstify -u low " " "mute" -h int:value:0 -h string:synchronous:volume
else
    # Remove leading zeros
    if [ "$volume" -lt "100" ]; then
        volume="${volume:1}"
    fi
    if [ "$volume" -lt "10" ]; then
         volume="${volume:1}"
    fi


    if [ "$volume" -gt "99" ]; then
        dunstify -u low " " "Volume: $volume%" -h int:value:$volume -h string:synchronous:volume 
    elif [ "$volume" -gt "65" ]; then
        dunstify -u low " " "Volume: $volume%" -h int:value:$volume -h string:synchronous:volume 
    elif [ "$volume" -gt "30" ]; then
        dunstify -u low " " "Volume: $volume%" -h int:value:$volume -h string:synchronous:volume 
    elif [ "$volume" -gt "10" ]; then
        dunstify -u low " " "Volume: $volume%" -h int:value:$volume -h string:synchronous:volume
    elif [ "$volume" -gt "0" ]; then
        dunstify -u low " " "Volume: $volume%" -h int:value:$volume -h string:synchronous:volume
    elif [ "$volume" -lt "1" ]; then
        dunstify -u low " " "Volume: $volume%" -h int:value:$volume -h string:synchronous:volume
    fi
fi
