#!/bin/bash

while true; do

    battery_level=$(cat /sys/class/power_supply/BAT0/capacity)
    status=$(cat /sys/class/power_supply/BAT0/status)

    if [ "$battery_level" -lt 15 ] && [ "$status" != "Charging" ]; then
        notify-send -u critical "" "Battery low: ${battery_level}%"
    fi

    sleep 180
done
