#!/bin/bash

layout=$(
  swaymsg -t get_inputs \
  | python3 -c '
import json,sys
for dev in json.load(sys.stdin):
    if dev.get("type") == "keyboard":
        print(dev.get("xkb_active_layout_name", ""))
        break
'
)

dunstify -u low " " "$layout"

